### ISSUE TITLE
Native Go SQLite Driver

### ISSUE THREAD

**Issue by AnalogJ** [risico/squeuelite#1]
Have you considered using https://gitlab.com/cznic/sqlite instead of github.com/mattn/go-sqlite3 ?

A native SQLite driver would make it easier to compile for multi-arch/cross-compiled apps

**Comment by risico** [comment]
Hi Jason, 

Initially I was using a native driver but the performance looked a bit lackluster, but might have been a problem with my initial implementation. 

I'll try again with a native driver and do some proper benchmarks. 


LE: 

Thanks for posting the first issue! 🥳

**Comment by risico** [comment]
I know a bit late, but I've finally added support for cgo/nocgo builds in #5 . 

Non-cgo versions can be chosen by setting the nocgo tag. `-tags nocgo`. Hopefully it helps!
