### ISSUE TITLE
feature request: ability to issue jobs to queue with included Time To Live duration

### ISSUE THREAD

**Issue by c-nv-s** [risico/squeuelite#2]
I was searching for a queue backed by sqlite that could offer this TTL/Deadline feature that is available in another Postgres-backed queue that I am also using (I'll include the project link below). I've copied the following issue request verbatim from that project to see if you could also consider it for this project because the feature is so very useful:

In some use cases it is very handy to be able to automatically remove a job from the queue if it has not been worked by a specified time duration.

This request is to implement an option/mechanism which allows the developer to specify a duration or Time To Live (TTL) for the job/s issued to the queue.

Personally, I'm not too precious about whether the developer is allowed to set the option at client creation or per request, but I understand that others may be more opinionated about it.

**Comment by c-nv-s** [comment]
implementation of the feature on the postgres-backed queue for reference:
https://github.com/acaloiaro/neoq/pull/59/files

**Comment by risico** [comment]
That's a good idea! I'll try and add it today. 

(sorry for the late reply, I just saw the issue)

**Comment by c-nv-s** [comment]
@risico did you manage to make any progress with this feature?

**Comment by risico** [comment]
Sorry I just noticed the message, for some reason Github is not sending me the notifications. But yeah, I've just pushed the final code for this: https://github.com/risico/squeuelite/pull/3

Will merge to master in a bit.
